package object;

import Main.GamePanel;
import entity.Projectile;
import entity.Entity;

import java.awt.*;

// Represents a Fireball projectile, extending the base Projectile class.
public class OBJ_Fireball extends Projectile {

    public OBJ_Fireball(GamePanel gp){
        super(gp);
        this.gp = gp;

        name = "Fireball";
        speed = 10;          // Movement speed of the fireball
        maxLife = 80;        // Max lifespan in frames (how far it can travel)
        life = maxLife;
        attack = 2;          // Damage value
        useCost = 1;         // Mana cost to cast this projectile
        alive = false;       // Initial state: not yet fired
        getImage();
    }

    // Loads the directional sprites for the fireball.
    public void getImage(){
        up1 = setup("/projectile/fireball_up_1", gp.tilesSize, gp.tilesSize);
        up2 = setup("/projectile/fireball_up_2", gp.tilesSize, gp.tilesSize);
        down1 = setup("/projectile/fireball_down_1", gp.tilesSize, gp.tilesSize);
        down2 = setup("/projectile/fireball_down_2", gp.tilesSize, gp.tilesSize);
        left1 = setup("/projectile/fireball_left_1", gp.tilesSize, gp.tilesSize);
        left2 = setup("/projectile/fireball_left_2", gp.tilesSize, gp.tilesSize);
        right1 = setup("/projectile/fireball_right_1", gp.tilesSize, gp.tilesSize);
        right2 = setup("/projectile/fireball_right_2", gp.tilesSize, gp.tilesSize);
    }

    /**
     * Checks if the entity attempting to use this projectile has enough mana.
     * @param user The entity (player or monster) attempting to cast.
     * @return true if the user has enough mana, false otherwise.
     */
    public boolean haveResource(Entity user){
        boolean haveResource = false;
        if(user.mana >= useCost){
            haveResource = true;
        }
        return haveResource;
    }

    /**
     * Deducts the mana cost from the user's current mana pool.
     * This is called right before the projectile is launched.
     * @param user The entity (player or monster) who cast the projectile.
     */
    public void subtractResource(Entity user){
        user.mana -= useCost;
    }

    // --- Particle Effects Properties ---
    // These methods define the characteristics of the particles generated by the fireball.

    public Color getPaticleColor(){
        // Fiery red/orange color
        Color color = new Color(245,50,0);
        return color;
    }

    public int getParticleSize(){
        int size = 10; // Particle size in pixels
        return size;
    }

    public int getParticleSpeed(){
        int speed = 1; // Speed at which particles move away from the source
        return speed;
    }

    public int getParticleMaxLife(){
        int maxLife = 20; // Lifespan of the individual particles in frames
        return maxLife;
    }
}