package object;

import Main.GamePanel;
import entity.Projectile;
import entity.Entity;

import java.awt.*;

// Represents a Rock projectile, used by entities (like MON_greenSlime) that rely on ammunition.
public class OBJ_BlueRock extends Projectile {

    public OBJ_BlueRock(GamePanel gp){
        super(gp);
        this.gp = gp; // Store GamePanel reference

        name = "Blue Rock";
        speed = 10;           // Movement speed of the rock
        maxLife = 90;        // Max lifespan in frames (how far it can travel before disappearing)
        life = maxLife;
        attack = 2;          // Damage value
        useCost = 1;         // Ammo cost to shoot this projectile
        alive = false;       // Initial state: not yet fired
        getImage();
    }

    // Loads the sprites for the rock. It uses a single, non-directional sprite
    // for all movements and animations (up1/up2, etc.).
    public void getImage(){
        up1 = setup("/projectile/rock_blue_down_2", gp.tilesSize, gp.tilesSize);
        up2 = setup("/projectile/rock_blue_down_2", gp.tilesSize, gp.tilesSize);
        down1 = setup("/projectile/rock_blue_down_2", gp.tilesSize, gp.tilesSize);
        down2 = setup("/projectile/rock_blue_down_2", gp.tilesSize, gp.tilesSize);
        left1 = setup("/projectile/rock_blue_down_2", gp.tilesSize, gp.tilesSize);
        left2 = setup("/projectile/rock_blue_down_2", gp.tilesSize, gp.tilesSize);
        right1 = setup("/projectile/rock_blue_down_2", gp.tilesSize, gp.tilesSize);
        right2 = setup("/projectile/rock_blue_down_2", gp.tilesSize, gp.tilesSize);
    }

    /**
     * Checks if the entity attempting to use this projectile has enough ammunition ('ammo').
     * @param user The entity (player or monster) attempting to fire the rock.
     * @return true if the user has enough ammo, false otherwise.
     */
    public boolean haveResource(Entity user){
        boolean haveResource = false;
        if(user.ammo >= useCost){
            haveResource = true;
        }
        return haveResource;
    }

    /**
     * Deducts the ammunition cost from the user's current ammo pool.
     * This is called right before the projectile is launched.
     * @param user The entity (player or monster) who fired the rock.
     */
    public void subtractResource(Entity user){
        user.ammo -= useCost;
    }

    // --- Particle Effects Properties ---
    // These methods define the characteristics of the particles generated by the rock upon impact/disappearance.

    public Color getPaticleColor(){
        // Earthy/dark color for a rock particle
        Color color = new Color(40,50,0);
        return color;
    }

    public int getParticleSize(){
        int size = 10; // Particle size in pixels
        return size;
    }

    public int getParticleSpeed(){
        int speed = 1; // Speed at which particles move away from the source
        return speed;
    }

    public int getParticleMaxLife(){
        int maxLife = 20; // Lifespan of the individual particles in frames
        return maxLife;
    }
}