package entity;

import Main.GamePanel;

import java.awt.*;

// Particle class used for visual effects generated by entities
public class Particles extends Entity {

    Entity generator; // The entity that generates this particle
    Color color;      // Color of the particle
    int size;         // Size (width & height) of the particle
    int xd;           // Horizontal direction/movement multiplier
    int yd;           // Vertical direction/movement multiplier

    // Constructor to initialize particle properties
    public Particles(GamePanel gp, Entity generator, Color color, int xd, int yd, int size, int speed, int maxLife) {
        super(gp);
        this.generator = generator;
        this.color = color;
        this.xd = xd;
        this.yd = yd;
        this.speed = speed;
        this.maxLife = maxLife;
        this.size = size;

        // Set initial life and starting position relative to generator
        life = maxLife;
        int offset = (gp.tilesSize/2) - (size/2); // Center particle on generator
        worldX = generator.worldX + offset;
        worldY = generator.worldY + offset;
    }

    // Update particle position and life
    public void update(){
        life--;                      // Decrease life each frame
        worldX += xd*speed;           // Move horizontally
        worldY += yd*speed;           // Move vertically

        if(life < maxLife/2){
            yd++;                     // Particle falls faster after half-life
        }

        if(life == 0){
            alive = false;            // Remove particle when life ends
        }
    }

    // Draw particle on the screen relative to the player
    public void draw(Graphics2D g2){
        int screenX = worldX - gp.player.worldX + gp.player.screenX;
        int screenY = worldY - gp.player.worldY + gp.player.screenY;
        g2.setColor(color);
        g2.fillRect(screenX, screenY, size, size);
    }
}
